CREATE TABLE "uoe_task_chain_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "uoe_task_chain_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"chainId" integer NOT NULL,
	"taskId" integer NOT NULL,
	"position" integer NOT NULL,
	CONSTRAINT "uoe_chain_item_position_check" CHECK ("uoe_task_chain_item"."position" between 1 and 9)
);
--> statement-breakpoint
CREATE TABLE "uoe_task_chain" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "uoe_task_chain_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"isDeleted" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
ALTER TABLE "uoe_task_chain_item" ADD CONSTRAINT "uoe_task_chain_item_chainId_uoe_task_chain_id_fk" FOREIGN KEY ("chainId") REFERENCES "public"."uoe_task_chain"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "uoe_task_chain_item" ADD CONSTRAINT "uoe_task_chain_item_taskId_uoe_task_id_fk" FOREIGN KEY ("taskId") REFERENCES "public"."uoe_task"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "uoe_chain_item_position_idx" ON "uoe_task_chain_item" USING btree ("chainId","position");--> statement-breakpoint
CREATE UNIQUE INDEX "uoe_chain_item_task_idx" ON "uoe_task_chain_item" USING btree ("chainId","taskId");--> statement-breakpoint
CREATE INDEX "uoe_chain_item_chain_id_idx" ON "uoe_task_chain_item" USING btree ("chainId");--> statement-breakpoint
CREATE INDEX "uoe_chain_item_task_id_idx" ON "uoe_task_chain_item" USING btree ("taskId");
