CREATE TYPE "public"."mock_exam_slot" AS ENUM('audio_1_4', 'audio_5', 'audio_6_11', 'reading_12', 'reading_13_19', 'uoe_all_topics', 'uoe_word_formation');--> statement-breakpoint
CREATE TABLE "mock_exam_attempt" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"mockExamId" integer NOT NULL,
	"snapshot" jsonb NOT NULL,
	"startedAt" timestamp with time zone NOT NULL,
	"expiresAt" timestamp with time zone NOT NULL,
	"completedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "mock_exam_part" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mock_exam_part_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"mockExamId" integer NOT NULL,
	"slot" "mock_exam_slot" NOT NULL,
	"audioTaskId" integer,
	"readingTaskId" integer,
	"uoeTaskChainId" integer,
	CONSTRAINT "mock_exam_part_resource_check" CHECK (num_nonnulls("mock_exam_part"."audioTaskId", "mock_exam_part"."readingTaskId", "mock_exam_part"."uoeTaskChainId") = 1),
	CONSTRAINT "mock_exam_part_slot_resource_check" CHECK ((
        ("mock_exam_part"."slot" in ('audio_1_4', 'audio_5', 'audio_6_11') and "mock_exam_part"."audioTaskId" is not null)
        or ("mock_exam_part"."slot" in ('reading_12', 'reading_13_19') and "mock_exam_part"."readingTaskId" is not null)
        or ("mock_exam_part"."slot" in ('uoe_all_topics', 'uoe_word_formation') and "mock_exam_part"."uoeTaskChainId" is not null)
      ))
);
--> statement-breakpoint
CREATE TABLE "mock_exam" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mock_exam_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"order" integer NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "user_result" ADD COLUMN "attemptKey" varchar(255);--> statement-breakpoint
ALTER TABLE "mock_exam_attempt" ADD CONSTRAINT "mock_exam_attempt_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mock_exam_attempt" ADD CONSTRAINT "mock_exam_attempt_mockExamId_mock_exam_id_fk" FOREIGN KEY ("mockExamId") REFERENCES "public"."mock_exam"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mock_exam_part" ADD CONSTRAINT "mock_exam_part_mockExamId_mock_exam_id_fk" FOREIGN KEY ("mockExamId") REFERENCES "public"."mock_exam"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mock_exam_part" ADD CONSTRAINT "mock_exam_part_audioTaskId_audio_task_id_fk" FOREIGN KEY ("audioTaskId") REFERENCES "public"."audio_task"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mock_exam_part" ADD CONSTRAINT "mock_exam_part_readingTaskId_reading_task_id_fk" FOREIGN KEY ("readingTaskId") REFERENCES "public"."reading_task"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mock_exam_part" ADD CONSTRAINT "mock_exam_part_uoeTaskChainId_uoe_task_chain_id_fk" FOREIGN KEY ("uoeTaskChainId") REFERENCES "public"."uoe_task_chain"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "mock_exam_attempt_user_idx" ON "mock_exam_attempt" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "mock_exam_attempt_expiry_idx" ON "mock_exam_attempt" USING btree ("expiresAt");--> statement-breakpoint
CREATE UNIQUE INDEX "mock_exam_part_slot_idx" ON "mock_exam_part" USING btree ("mockExamId","slot");--> statement-breakpoint
CREATE INDEX "mock_exam_part_audio_task_idx" ON "mock_exam_part" USING btree ("audioTaskId");--> statement-breakpoint
CREATE INDEX "mock_exam_part_reading_task_idx" ON "mock_exam_part" USING btree ("readingTaskId");--> statement-breakpoint
CREATE INDEX "mock_exam_part_uoe_chain_idx" ON "mock_exam_part" USING btree ("uoeTaskChainId");--> statement-breakpoint
CREATE UNIQUE INDEX "mock_exam_title_idx" ON "mock_exam" USING btree ("title");--> statement-breakpoint
CREATE UNIQUE INDEX "mock_exam_order_idx" ON "mock_exam" USING btree ("order");--> statement-breakpoint
CREATE UNIQUE INDEX "user_result_attempt_key_idx" ON "user_result" USING btree ("attemptKey");--> statement-breakpoint
CREATE INDEX "user_result_latest_activity_idx" ON "user_result" USING btree ("userId","activity_type","activityId","createdAt");