CREATE TABLE "training_topic" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "training_topic_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"category" varchar(100) NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
ALTER TABLE "audio_task_first" RENAME COLUMN "audio_url" TO "audioUrl";--> statement-breakpoint
ALTER TABLE "audio_task_first" ADD COLUMN "topicId" integer;--> statement-breakpoint
ALTER TABLE "reading_task_first" ADD COLUMN "topicId" integer;--> statement-breakpoint
ALTER TABLE "uoe_task" DROP COLUMN "topic";--> statement-breakpoint
ALTER TABLE "uoe_task" ADD "topicId" integer;--> statement-breakpoint
ALTER TABLE "audio_task_first" ADD CONSTRAINT "audio_task_first_topicId_training_topic_id_fk" FOREIGN KEY ("topicId") REFERENCES "public"."training_topic"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reading_task_first" ADD CONSTRAINT "reading_task_first_topicId_training_topic_id_fk" FOREIGN KEY ("topicId") REFERENCES "public"."training_topic"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "uoe_task" ADD CONSTRAINT "uoe_task_topicId_training_topic_id_fk" FOREIGN KEY ("topicId") REFERENCES "public"."training_topic"("id") ON DELETE set null ON UPDATE no action;

-- Seed initial topics
INSERT INTO "training_topic" (title, category) VALUES
  ('Задания 1-4', 'audio'),
  ('Задание 5', 'audio'),
  ('Задания 6-11', 'audio'),
  ('Задание 12', 'reading'),
  ('Задания 13-19', 'reading'),
  ('По всем темам', 'use-of-english'),
  ('Словообразование', 'use-of-english'),
  ('Множественное число существительных', 'use-of-english'),
  ('Порядковые числительные', 'use-of-english'),
  ('Объектные местоимения', 'use-of-english'),
  ('Степени сравнения', 'use-of-english'),
  ('Притяжательные и возвратные местоимения', 'use-of-english'),
  ('Пассивный залог', 'use-of-english'),
  ('Глагол to be', 'use-of-english'),
  ('I wish + V2', 'use-of-english'),
  ('Модальные глаголы', 'use-of-english'),
  ('Условное предложение (реальное)', 'use-of-english'),
  ('Условное предложение (нереальное)', 'use-of-english'),
  ('Настоящее Простое/Продолженное', 'use-of-english'),
  ('Настоящее/Прошедшее Совершенное', 'use-of-english'),
  ('Прошедшее Простое', 'use-of-english'),
  ('Прошедшее Продолженное', 'use-of-english'),
  ('Будущее Простое', 'use-of-english'),
  ('Would + V', 'use-of-english');
